### ISSUE TITLE
How do i fix this issue

### ISSUE THREAD

**Issue by cooldude315** [Choru5/ML-Aimbot-Halo-Infinite#3]
![image](https://user-images.githubusercontent.com/117041200/202861060-31025479-7907-4a85-9331-860b275e8cc4.png)

**Comment by cooldude315** [comment]
when i click off of halo it spikes up to 30

**Comment by cooldude315** [comment]
i fixed that issue but how do i fix it when the aim just goes bonkers like everywhere

**Comment by TonttuHomo** [comment]
Resolution issue maybe

**Comment by OfficialProtonDev** [comment]
Hi, try turning up the detection confidence and reducing the value responsible for the radius in which it will move to detections from, also try tweaking sensitivity, otherwise you probably a resolution issue like the other person suggested.
