### ISSUE TITLE
Cant fulfill installing the required libraries

### ISSUE THREAD

**Issue by Olibier** [Choru5/ML-Aimbot-Halo-Infinite#5]
ERROR: Ignored the following versions that require a different python version: 1.11.0 Requires-Python <3.13,>=3.9; 1.11.0rc1 Requires-Python <3.13,>=3.9; 1.11.0rc2 Requires-Python <3.13,>=3.9; 1.11.1 Requires-Python <3.13,>=3.9; 1.11.2 Requires-Python <3.13,>=3.9; 1.25.0 Requires-Python >=3.9; 1.25.0rc1 Requires-Python >=3.9; 1.25.1 Requires-Python >=3.9; 1.25.2 Requires-Python >=3.9; 1.26.0b1 Requires-Python <3.13,>=3.9; 2.0.0 Requires-Python >=3.8.1,<4.0; 2.0.1 Requires-Python >=3.8.1,<4.0; 2.0.2 Requires-Python >=3.8.1,<4.0; 2.0.3 Requires-Python >=3.8.1,<4.0; 2.0.4 Requires-Python >=3.8.1,<4.0; 2.0.5 Requires-Python >=3.8.1,<4.0; 2.0.6 Requires-Python >=3.8.1,<4.0; 2.1.0 Requires-Python >=3.9; 2.1.0rc0 Requires-Python >=3.9; 3.8.0rc1 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement torch==1.11.0+cu113 (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1)
ERROR: No matching distribution found for torch==1.11.0+cu113

**Comment by OfficialProtonDev** [comment]
Yeah I had that problem once, I believe you just need to use python 3.8.9, and make sure no other python versions are installed.

**Comment by sp7r** [comment]
I was having the same issue. I was able to get it to work by running this command

```python
pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio===0.11.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html

``` 

and then rerunning the requirements.txt

-Just curious, what are the best settings that you have found to have the smoothest lock-on? 

I have have been playing with settings for a while and currently have:
detection_threshold = 0.93 
headshot_multiplier = 0.75 
movement_amp = 0.75
lock_distance = 75

but it still feels erratic and jerks around too quickly, just trying to get a moderate "aim assist" feel.

**Comment by OfficialProtonDev** [comment]
> I was having the same issue. I was able to get it to work by running this command
> 
> ```python
> pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio===0.11.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
> ```
> 
> and then rerunning the requirements.txt
> 
> -Just curious, what are the best settings that you have found to have the smoothest lock-on?
> 
> I have have been playing with settings for a while and currently have: detection_threshold = 0.93 headshot_multiplier = 0.75 movement_amp = 0.75 lock_distance = 75
> 
> but it still feels erratic and jerks around too quickly, just trying to get a moderate "aim assist" feel.

I haven't played around with this project in a long time, so I don't remember what settings I was running. If you have a decent knowledge of coding / chatgpt there are A LOT of updates that can be made to make this project work a lot better, however Halo Infinite is a rather bad game to use this on, games like Valorant (needs custom mouse move method) work extremely well with this program, as the enemy movement is a lot slower and more manageable to detect and move to.

**Comment by fettyblanco59** [comment]
Im getting these errors "Traceback (most recent call last):
  File "deploy.py", line 294, in <module>
    main(run_loop=True, modelPath=chosenModel, gameWindow=gw, lockDist=ld, lockSpeed=ls)
  File "deploy.py", line 158, in main
    model = torch.hub.load('./yolov5', 'custom', source='local', path=modelPath, force_reload=True)
  File "C:\Users\Dale\anaconda\envs\pytorch-gpu\lib\site-packages\torch\hub.py", line 566, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\Users\Dale\anaconda\envs\pytorch-gpu\lib\site-packages\torch\hub.py", line 595, in _load_local
    model = entry(*args, **kwargs)
  File "./yolov5\hubconf.py", line 71, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
  File "./yolov5\hubconf.py", line 31, in _create
    from models.common import AutoShape, DetectMultiBackend
ModuleNotFoundError: No module named 'models' " 

Then when I try to install models & base modules I get this " (pytorch-gpu) C:\Users\Dale\OneDrive\Desktop\ML-Aimbot-Halo-Infinite-main>pip install models
Collecting models
  Using cached models-0.9.3.tar.gz (16 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Dale\AppData\Local\Temp\pip-install-c5_p2rzn\models_3a080c6a390a40768fdb2ee7e5ebe3a1\setup.py", line 25, in <module>
          import models
        File "C:\Users\Dale\AppData\Local\Temp\pip-install-c5_p2rzn\models_3a080c6a390a40768fdb2ee7e5ebe3a1\models\__init__.py", line 23, in <module>
          from base import *
      ModuleNotFoundError: No module named 'base'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details. " Any idea what I may be able to do?

**Comment by OfficialProtonDev** [comment]
> Im getting these errors "Traceback (most recent call last): File "deploy.py", line 294, in main(run_loop=True, modelPath=chosenModel, gameWindow=gw, lockDist=ld, lockSpeed=ls) File "deploy.py", line 158, in main model = torch.hub.load('./yolov5', 'custom', source='local', path=modelPath, force_reload=True) File "C:\Users\Dale\anaconda\envs\pytorch-gpu\lib\site-packages\torch\hub.py", line 566, in load model = _load_local(repo_or_dir, model, *args, **kwargs) File "C:\Users\Dale\anaconda\envs\pytorch-gpu\lib\site-packages\torch\hub.py", line 595, in _load_local model = entry(*args, **kwargs) File "./yolov5\hubconf.py", line 71, in custom return _create(path, autoshape=autoshape, verbose=_verbose, device=device) File "./yolov5\hubconf.py", line 31, in _create from models.common import AutoShape, DetectMultiBackend ModuleNotFoundError: No module named 'models' "
> 
> Then when I try to install models & base modules I get this " (pytorch-gpu) C:\Users\Dale\OneDrive\Desktop\ML-Aimbot-Halo-Infinite-main>pip install models Collecting models Using cached models-0.9.3.tar.gz (16 kB) Preparing metadata (setup.py) ... error error: subprocess-exited-with-error
> 
> × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [8 lines of output] Traceback (most recent call last): File "", line 2, in File "", line 34, in File "C:\Users\Dale\AppData\Local\Temp\pip-install-c5_p2rzn\models_3a080c6a390a40768fdb2ee7e5ebe3a1\setup.py", line 25, in import models File "C:\Users\Dale\AppData\Local\Temp\pip-install-c5_p2rzn\models_3a080c6a390a40768fdb2ee7e5ebe3a1\models__init__.py", line 23, in from base import * ModuleNotFoundError: No module named 'base' [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> 
> × Encountered error while generating package metadata. ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for details. " Any idea what I may be able to do?

Pretty sure you need the new yolov5 repo to replace the current yolov5 folder, as some stuff has changed and 'models' is a folder in the yolov5 folder, not a library to be pip installed.
